### ISSUE TITLE
cf create-service gives 502 "Registered endpoint failed to handle the request"

### ISSUE THREAD

**Issue by rifung** [GoogleCloudPlatform/gcp-service-broker#106]
I've been following the walkthrough and am hitting an issue on the create-service step.

When running the command I see

```

Creating service instance awwvision-storage in org nextdemo / space development as minesasecret@gmail.com...
FAILED
Server error, status code: 502, error code: 10001, message: The service broker returned an invalid response for the request to https://gcp-sb.cfapps.io/v2/service_instances/38e9c946-c29b-4a5c-a26a-d5845f05d073?accepts_incomplete=true. Status Code: 502 Bad Gateway, Body: 502 Bad Gateway: Registered endpoint failed to handle the request.
```

which doesn't say much but the logs show

```2017-02-14T10:46:34.432-08:00 [APP/PROC/WEB/0] [ERR] /tmp/cache/go1.7.4/go/src/net/http/server.go:1491 +0x12a
2017-02-14T10:46:34.432-08:00 [APP/PROC/WEB/0] [ERR] /tmp/cache/go1.7.4/go/src/runtime/panic.go:458 +0x243
2017-02-14T10:46:34.432-08:00 [APP/PROC/WEB/0] [ERR] gcp-service-broker/brokerapi.serviceBrokerHandler.provision(0x10832c0, 0xc4201621c0, 0x1083920, 0xc4201419e0, 0x1080740, 0xc4201b8270, 0xc4200c43c0)
2017-02-14T10:46:34.432-08:00 [APP/PROC/WEB/0] [ERR] /tmp/tmp.zgHYtH3cKs/.go/src/gcp-service-broker/brokerapi/api.go:73 +0x69
2017-02-14T10:46:34.432-08:00 [APP/PROC/WEB/0] [ERR] /tmp/tmp.zgHYtH3cKs/.go/src/gcp-service-broker/vendor/github.com/gorilla/mux/mux.go:103 +0x255
2017-02-14T10:46:34.432-08:00 [APP/PROC/WEB/0] [ERR] net/http.(*ServeMux).ServeHTTP(0x109a980, 0x1080740, 0xc4201b8270, 0xc4200c43c0)
2017-02-14T10:46:34.432-08:00 [APP/PROC/WEB/0] [ERR] goroutine 1721 [running]:
2017-02-14T10:46:34.432-08:00 [APP/PROC/WEB/0] [ERR] panic(0xa89660, 0xc42000c090)
2017-02-14T10:46:34.432-08:00 [APP/PROC/WEB/0] [ERR] /tmp/tmp.zgHYtH3cKs/.go/src/gcp-service-broker/brokerapi/brokers/gcp_service_broker.go:216 +0x388
2017-02-14T10:46:34.432-08:00 [APP/PROC/WEB/0] [ERR] gcp-service-broker/brokerapi.(serviceBrokerHandler).(gcp-service-broker/brokerapi.provision)-fm(0x1080740, 0xc4201b8270, 0xc4200c43c0)
2017-02-14T10:46:34.432-08:00 [APP/PROC/WEB/0] [ERR] net/http.HandlerFunc.ServeHTTP(0xc42017eb70, 0x1080740, 0xc4201b8270, 0xc4200c43c0)
2017-02-14T10:46:34.432-08:00 [APP/PROC/WEB/0] [ERR] gcp-service-broker/auth.(*Wrapper).Wrap.func1(0x1080740, 0xc4201b8270, 0xc4200c43c0)
2017-02-14T10:46:34.432-08:00 [APP/PROC/WEB/0] [ERR] /tmp/tmp.zgHYtH3cKs/.go/src/gcp-service-broker/auth/auth.go:43 +0x85
2017-02-14T10:46:34.432-08:00 [APP/PROC/WEB/0] [ERR] /tmp/cache/go1.7.4/go/src/net/http/server.go:1726 +0x44
2017-02-14T10:46:34.432-08:00 [APP/PROC/WEB/0] [ERR] gcp-service-broker/brokerapi/brokers.(*GCPAsyncServiceBroker).Provision(0xc4201621c0, 0xc42014013a, 0x24, 0xc42017e2a0, 0x24, 0xc42017e390, 0x24, 0xc42017e3c0, 0x24, 0xc42017e3f0, ...)
2017-02-14T10:46:34.432-08:00 [APP/PROC/WEB/0] [ERR] /tmp/tmp.zgHYtH3cKs/.go/src/gcp-service-broker/brokerapi/api.go:118 +0x721
2017-02-14T10:46:34.432-08:00 [APP/PROC/WEB/0] [ERR] gcp-service-broker/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc4202267d0, 0x1080740, 0xc4201b8270, 0xc4200c43c0)
2017-02-14T10:46:34.432-08:00 [APP/PROC/WEB/0] [ERR] 2017/02/14 18:46:34 http: panic serving 10.10.81.4:51650: runtime error: invalid memory address or nil pointer dereference
2017-02-14T10:46:34.432-08:00 [APP/PROC/WEB/0] [ERR] net/http.(*conn).serve.func1(0xc420166080)
2017-02-14T10:46:34.432-08:00 [APP/PROC/WEB/0] [ERR] net/http.HandlerFunc.ServeHTTP(0xc4204bcdc0, 0x1080740, 0xc4201b8270, 0xc4200c43c0)
2017-02-14T10:46:34.433-08:00 [APP/PROC/WEB/0] [ERR] net/http.serverHandler.ServeHTTP(0xc420190f80, 0x1080740, 0xc4201b8270, 0xc4200c43c0)
2017-02-14T10:46:34.433-08:00 [APP/PROC/WEB/0] [ERR] net/http.(*conn).serve(0xc420166080, 0x1080fc0, 0xc420458b40)
2017-02-14T10:46:34.433-08:00 [APP/PROC/WEB/0] [ERR] /tmp/cache/go1.7.4/go/src/net/http/server.go:2293 +0x44d
2017-02-14T10:46:34.433-08:00 [APP/PROC/WEB/0] [ERR] /tmp/cache/go1.7.4/go/src/net/http/server.go:2202 +0x7d
2017-02-14T10:46:34.433-08:00 [APP/PROC/WEB/0] [ERR] /tmp/cache/go1.7.4/go/src/net/http/server.go:2022 +0x7f
2017-02-14T10:46:34.433-08:00 [APP/PROC/WEB/0] [ERR] /tmp/cache/go1.7.4/go/src/net/http/server.go:1579 +0x4b7
2017-02-14T10:46:34.433-08:00 [APP/PROC/WEB/0] [ERR] created by net/http.(*Server).Serve
```

**Comment by rifung** [comment]
This was caused because I changed the service name in the manifest.yml because create-service-broker required that the service names were unique but I didn't change the names in the models package, so it crashes because gcpBroker.ServiceBrokerMap[serviceId] is nil

`gcpBroker.ShouldProvisionAsync = gcpBroker.ServiceBrokerMap[serviceId].Async()`
